doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    types:
      itinerary_uuid: Academy\Itinerary\Infrastructure\Persistence\Doctrine\ItineraryUuidType
      activity_uuid: Academy\Activity\Infrastructure\Persistence\Doctrine\ActivityUuidType
      activity_itinerary_uuid: Academy\ActivityItinerary\Infrastructure\Persistence\Doctrine\ActivityItineraryUuidType
      student_uuid: Academy\Student\Infrastructure\Persistence\Doctrine\StudentUuidType
      evaluation_uuid: Academy\Evaluation\Infrastructure\Persistence\Doctrine\EvaluationUuidType

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Itinerary:
        type: xml
        dir: "%kernel.project_dir%/../src/Itinerary/Infrastructure/Persistence/Doctrine"
        is_bundle: false
        prefix: 'Academy\Itinerary\Domain'
        alias: Academy\Itinerary\Domain

      Activity:
        type: xml
        dir: "%kernel.project_dir%/../src/Activity/Infrastructure/Persistence/Doctrine"
        is_bundle: false
        prefix: 'Academy\Activity\Domain'
        alias: Academy\Activity\Domain

      ActivityItinerary:
        type: xml
        dir: "%kernel.project_dir%/../src/ActivityItinerary/Infrastructure/Persistence/Doctrine"
        is_bundle: false
        prefix: 'Academy\ActivityItinerary\Domain'
        alias: Academy\ActivityItinerary\Domain

      Student:
        type: xml
        dir: "%kernel.project_dir%/../src/Student/Infrastructure/Persistence/Doctrine"
        is_bundle: false
        prefix: 'Academy\Student\Domain'
        alias: Academy\Student\Domain

      Evaluation:
        type: xml
        dir: "%kernel.project_dir%/../src/Evaluation/Infrastructure/Persistence/Doctrine"
        is_bundle: false
        prefix: 'Academy\Evaluation\Domain'
        alias: Academy\Evaluation\Domain