<?php

namespace ContainerElRoQq0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DefaultXmlMetadataDriverService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.default_xml_metadata_driver' shared service.
     *
     * @return \Doctrine\ORM\Mapping\Driver\SimplifiedXmlDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/MappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/FileDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/SimplifiedXmlDriver.php';

        $container->privates['doctrine.orm.default_xml_metadata_driver'] = $instance = new \Doctrine\ORM\Mapping\Driver\SimplifiedXmlDriver([(\dirname(__DIR__, 4).'/src/Itinerary/Infrastructure/Persistence/Doctrine') => 'Academy\\Itinerary\\Domain', (\dirname(__DIR__, 4).'/src/Activity/Infrastructure/Persistence/Doctrine') => 'Academy\\Activity\\Domain', (\dirname(__DIR__, 4).'/src/ActivityItinerary/Infrastructure/Persistence/Doctrine') => 'Academy\\ActivityItinerary\\Domain']);

        $instance->setGlobalBasename('mapping');

        return $instance;
    }
}
