<?php

namespace ContainerElRoQq0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItineraryGuardService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Academy\Itinerary\Domain\ItineraryGuard' shared autowired service.
     *
     * @return \Academy\Itinerary\Domain\ItineraryGuard
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Itinerary/Domain/IItineraryGuard.php';
        include_once \dirname(__DIR__, 4).'/src/Itinerary/Domain/ItineraryGuard.php';

        return $container->privates['Academy\\Itinerary\\Domain\\ItineraryGuard'] = new \Academy\Itinerary\Domain\ItineraryGuard(($container->privates['Academy\\Itinerary\\Infrastructure\\Persistence\\ItineraryRepositoryMysql'] ?? $container->load('getItineraryRepositoryMysqlService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
