#activities_itinerary_get_by_id:
#  path: /api/itineraries/{id}/activity
#  controller: Academy\ActivityItinerary\EntryPoint\Http\Controller\ListingActivityController
#  defaults: { auth: false }
#  methods:  [GET|HEAD]
#
#itinerary_store_activity:
#  path: /api/itineraries/{id}/activity
#  controller: Academy\ActivityItinerary\EntryPoint\Http\Controller\AddActivityController
#  defaults: { auth: false }
#  methods:  [POST]