controllers_itinerary:
  resource: ../../../src/Itinerary/EntryPoint/Http/Controller
  type: annotation

controllers_student:
  resource: ../../../src/Student/EntryPoint/Http/Controller
  type: annotation