<?php

namespace ContainerOzJKxMO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityGuardService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Academy\Activity\Domain\ActivityGuard' shared autowired service.
     *
     * @return \Academy\Activity\Domain\ActivityGuard
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Activity/Domain/IActivityGuard.php';
        include_once \dirname(__DIR__, 4).'/src/Activity/Domain/ActivityGuard.php';

        return $container->privates['Academy\\Activity\\Domain\\ActivityGuard'] = new \Academy\Activity\Domain\ActivityGuard(($container->privates['Academy\\Activity\\Infrastructure\\Persistence\\ActivityRepositoryMysql'] ?? $container->load('getActivityRepositoryMysqlService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
