<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerElRoQq0\Academy_App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerElRoQq0/Academy_App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerElRoQq0.legacy');

    return;
}

if (!\class_exists(Academy_App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerElRoQq0\Academy_App_KernelDevDebugContainer::class, Academy_App_KernelDevDebugContainer::class, false);
}

return new \ContainerElRoQq0\Academy_App_KernelDevDebugContainer([
    'container.build_hash' => 'ElRoQq0',
    'container.build_id' => '83602c30',
    'container.build_time' => 1610927673,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerElRoQq0');
