<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOzJKxMO\Academy_App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOzJKxMO/Academy_App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOzJKxMO.legacy');

    return;
}

if (!\class_exists(Academy_App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOzJKxMO\Academy_App_KernelDevDebugContainer::class, Academy_App_KernelDevDebugContainer::class, false);
}

return new \ContainerOzJKxMO\Academy_App_KernelDevDebugContainer([
    'container.build_hash' => 'OzJKxMO',
    'container.build_id' => 'd9a505e1',
    'container.build_time' => 1610927450,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOzJKxMO');
