<?php

namespace ContainerA1mKFZF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShowListActivityHandlerService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Academy\ActivityItinerary\Application\ShowListActivity\ShowListActivityHandler' shared autowired service.
     *
     * @return \Academy\ActivityItinerary\Application\ShowListActivity\ShowListActivityHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/ActivityItinerary/Application/ShowListActivity/ShowListActivityHandler.php';

        return $container->privates['Academy\\ActivityItinerary\\Application\\ShowListActivity\\ShowListActivityHandler'] = new \Academy\ActivityItinerary\Application\ShowListActivity\ShowListActivityHandler(($container->privates['Academy\\ActivityItinerary\\Domain\\ActivityFinder'] ?? $container->load('getActivityFinderService')));
    }
}
