<?php

namespace ContainerCrknBAG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityRepositoryMysqlService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Academy\Activity\Infrastructure\Persistence\ActivityRepositoryMysql' shared autowired service.
     *
     * @return \Academy\Activity\Infrastructure\Persistence\ActivityRepositoryMysql
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Activity/Domain/ActivityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Activity/Infrastructure/Persistence/ActivityRepositoryMysql.php';

        return $container->privates['Academy\\Activity\\Infrastructure\\Persistence\\ActivityRepositoryMysql'] = new \Academy\Activity\Infrastructure\Persistence\ActivityRepositoryMysql(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
