<?php

namespace ContainerDO1caQW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_J4KSUkService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.J4_kSUk' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor.J4_kSUk'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['Academy\\ActivityItinerary\\Application\\AddActivity\\AddActivityHandler'] ?? $container->load('getAddActivityHandlerService')), []);
    }
}
