<?php

namespace ContainerRkm4haE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityAdderService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Academy\ActivityItinerary\Domain\ActivityAdder' shared autowired service.
     *
     * @return \Academy\ActivityItinerary\Domain\ActivityAdder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ActivityItinerary/Domain/ActivityAdder.php';

        return $container->privates['Academy\\ActivityItinerary\\Domain\\ActivityAdder'] = new \Academy\ActivityItinerary\Domain\ActivityAdder(($container->privates['Academy\\Itinerary\\Domain\\ItineraryGuard'] ?? $container->load('getItineraryGuardService')), ($container->privates['Academy\\Activity\\Domain\\ActivityGuard'] ?? $container->load('getActivityGuardService')), ($container->privates['Academy\\ActivityItinerary\\Infrastructure\\Persistence\\ActivityItineraryRepositoryMysql'] ?? $container->load('getActivityItineraryRepositoryMysqlService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
