<?php

namespace ContainerRkm4haE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityFinderService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Academy\ActivityItinerary\Domain\ActivityFinder' shared autowired service.
     *
     * @return \Academy\ActivityItinerary\Domain\ActivityFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ActivityItinerary/Domain/ActivityFinder.php';

        return $container->privates['Academy\\ActivityItinerary\\Domain\\ActivityFinder'] = new \Academy\ActivityItinerary\Domain\ActivityFinder(($container->privates['Academy\\Itinerary\\Domain\\ItineraryGuard'] ?? $container->load('getItineraryGuardService')), ($container->privates['Academy\\ActivityItinerary\\Infrastructure\\Persistence\\ActivityItineraryRepositoryMysql'] ?? $container->load('getActivityItineraryRepositoryMysqlService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
