<?php

namespace ContainerRkm4haE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityItineraryRepositoryMysqlService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Academy\ActivityItinerary\Infrastructure\Persistence\ActivityItineraryRepositoryMysql' shared autowired service.
     *
     * @return \Academy\ActivityItinerary\Infrastructure\Persistence\ActivityItineraryRepositoryMysql
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ActivityItinerary/Domain/ActivityItineraryRepository.php';
        include_once \dirname(__DIR__, 4).'/src/ActivityItinerary/Infrastructure/Persistence/ActivityItineraryRepositoryMysql.php';

        return $container->privates['Academy\\ActivityItinerary\\Infrastructure\\Persistence\\ActivityItineraryRepositoryMysql'] = new \Academy\ActivityItinerary\Infrastructure\Persistence\ActivityItineraryRepositoryMysql(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
