<?php

namespace ContainerRkm4haE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_MessengerDebugService extends Academy_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.messenger_debug' shared service.
     *
     * @return \Symfony\Component\Messenger\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Command/DebugCommand.php';

        $container->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(['messenger.bus.default' => ['Academy\\ActivityItinerary\\Application\\AddActivity\\AddActivityCommand' => [0 => [0 => 'Academy\\ActivityItinerary\\Application\\AddActivity\\AddActivityHandler', 1 => []]], 'Academy\\ActivityItinerary\\Application\\ShowListActivity\\ShowListActivityCommand' => [0 => [0 => 'Academy\\ActivityItinerary\\Application\\ShowListActivity\\ShowListActivityHandler', 1 => []]]]]);

        $instance->setName('debug:messenger');

        return $instance;
    }
}
